# frozen_string_literal: true

class SeedWhereIsMyFriendsInterestCatalogue < ActiveRecord::Migration[8.0]
  def up
    return unless Migration::Helpers.existing_site?

    execute <<~SQL
      INSERT INTO tags (name, created_at, updated_at)
      VALUES
        ('纯实践', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('惩戒管教', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('游戏互动', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('情景剧情', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('氛围轻松', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('氛围严肃', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('轻度', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('中度', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('中重度', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('重度', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('主动', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('被动', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('双向', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('Brat互动', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('仪式感', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('羞耻感', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('压迫感', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('被控制感', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('服从感', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('被关怀感', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('安全感', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('规则约定', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('任务挑战', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('罚站', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('罚跪', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('写检查', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('罚抄', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('事后复盘', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('身体束缚', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('眼罩', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('特殊服饰', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('多人互动', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('徒手', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('皮具', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('戒尺', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('轻板', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('重板', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('藤条', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('软质工具', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('臀部', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('大腿后侧', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('大腿前侧', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('手心', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('脚心', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('新手入门', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('实践分享', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('DIY交流', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('小说故事', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('游戏创作', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('学术讨论', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('安全与边界', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('同城交流', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('线上交流', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('一对一交流', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('社群讨论', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
        ('暂不实践', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
      ON CONFLICT (name) DO NOTHING
    SQL
  end

  def down
    raise ActiveRecord::IrreversibleMigration
  end
end
