name: Discourse Plugin

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    uses: discourse/.github/.github/workflows/discourse-plugin.yml@v1
    with:
      core_ref: 7c06c1528ed9571d7407fa32259d77e1853c64d5

  latest:
    uses: discourse/.github/.github/workflows/discourse-plugin.yml@v1
